# Generated by Django 3.2.5 on 2021-07-10 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toys',
            new_name='Toy',
        ),
    ]
